stages:
  - build
build_latex:
  stage: build
  image: texlive/texlive:latest
  script:
    - cp fonts/* /usr/share/fonts
    - fc-cache -f -v
    - python3 generate.py
  artifacts:
    paths:
      - "*.pdf"
