name: PDF
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            cp fonts/* /usr/share/fonts
            fc-cache -f -v
            python3 generate.py
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dream-of-the-red-chamber.pdf
          asset_name: dream-of-the-red-chamber.pdf
          tag: latest
          overwrite: true
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: journey-to-the-west.pdf
          asset_name: journey-to-the-west.pdf
          tag: latest
          overwrite: true
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: romance-of-the-three-kingdoms.pdf
          asset_name: romance-of-the-three-kingdoms.pdf
          tag: latest
          overwrite: true
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: the-plum-in-the-golden-vase.pdf
          asset_name: the-plum-in-the-golden-vase.pdf
          tag: latest
          overwrite: true
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: water-margin.pdf
          asset_name: water-margin.pdf
          tag: latest
          overwrite: true
