name: PDF
on:
  push:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Compile
        uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: |
            cp fonts/* /usr/share/fonts
            fc-cache -f -v
            python3 generate.py
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.pdf"
          file_glob: true
          tag: latest
          overwrite: true
